#
# This is the appspec.yml file for the AWS CodeDeploy
#
version: 0.0
os: linux
files:
- source: /src/
  destination: /home/ec2-user/node-website/src
- source: /package.json
  destination: /home/ec2-user/node-website
- source: /node_modules
  destination: /home/ec2-user/node-website/node_modules
hooks:
  ApplicationStop:
  - location: scripts/stop_server.sh
    timeout: 300
    runas: root
  BeforeInstall:
  - location: scripts/before.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: scripts/after_install.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 300
    runas: root
  ValidateService:
  - location: scripts/validate.sh
    timeout: 30
    runas: root